"use client";
import {useState} from "react";
const capabilities=[
 ["Multi-account Connections","Connect the correct business identity for each workflow","READY TO CONNECT"],
 ["Appshots / Visual Support","Use application snapshots as evidence for diagnosis and implementation support","AVAILABLE"],
 ["Company Knowledge & Sync","Bring approved company sources into HQ intelligence without duplicating every file","DESIGN READY"],
 ["Work / Event Automation","Turn supported app events into AI jobs, approvals and actions","ORCHESTRATION"],
 ["Plugin Capability Library","Reusable skills + apps + templates selected per venture and job","LIBRARY"],
 ["Connected Data Intelligence","Analyse venture data with company definitions and operating context","INTELLIGENCE"],
 ["Project / Context Import","Ingest supported project/context sources into an HQ workspace with provenance","INGESTION"]
];
export default function AstraControl(){const [selected,setSelected]=useState(0);return <div className="astraControl"><section className="exec-hero"><div><p className="eyebrow">ASTRA ORCHESTRATION LAYER</p><h2>Connect intelligence to the work already happening across Bankole HQ.</h2><p>HQ decides what needs doing, which account and capability should handle it, what requires approval, and what evidence returns to the venture.</p></div><span className="statusChip">CONTROL LAYER</span></section><section className="metric-grid four"><article className="metric"><small>CAPABILITY ROUTES</small><b>7</b><p>native · plugin · existing system · custom</p></article><article className="metric"><small>ACCOUNT CONTEXT</small><b>Per job</b><p>choose the right connected identity</p></article><article className="metric"><small>KNOWLEDGE</small><b>Scoped</b><p>venture and company context</p></article><article className="metric"><small>EXECUTION</small><b>Gated</b><p>approval before consequential actions</p></article></section><section className="split"><div className="panel"><h3>Capability resolver</h3><p className="note">HQ should reuse the cheapest reliable capability before commissioning custom work.</p><div className="capabilityList">{capabilities.map((c,i)=><button key={c[0]} onClick={()=>setSelected(i)} className={selected===i?"capRow selected":"capRow"}><span><b>{c[0]}</b><small>{c[1]}</small></span><em>{c[2]}</em></button>)}</div></div><div className="panel"><h3>{capabilities[selected][0]}</h3><p>{capabilities[selected][1]}.</p><div className="resolverFlow"><b>1 · Understand the job</b><span>venture, goal, sensitivity and evidence</span><b>2 · Resolve capability</b><span>native ChatGPT → plugin → existing software → BAA module → custom</span><b>3 · Resolve account</b><span>use the authorised business account for this job</span><b>4 · Execute or request approval</b><span>safe internal work runs; consequential external action waits</span><b>5 · Return evidence</b><span>result, source and status filter back into HQ</span></div></div></section><section className="panel wide"><h3>Connection & sync registry</h3><div className="connectionGrid">{["Gmail","Google Calendar","Google Drive","GitHub","Vercel","BAA","FireComplianceUK"].map((x,i)=><article key={x}><b>{x}</b><small>{i<4?"Connected capability":"HQ system"}</small><span>{i<4?"Account-aware":"Venture-aware"}</span></article>)}</div><p className="note">This registry is the HQ control surface. It does not pretend an account or provider is connected until the underlying integration confirms it.</p></section></div>}