"use client";
import { useMemo, useState } from "react";

type GeneratedPiece={title:string;format:string;hook:string;concept:string;caption:string;cta:string;productionBrief:string;purpose:string;skillsUsed:string[];evidenceUsed?:string[]};
type Generation={brand:string;objective:string;strategy:string;skillsUsed:string[];evidenceSummary:string;pieces:GeneratedPiece[]};

const brands=["Bubble Leisure","SAYAH","Lucky Studios","Brilliant AI Automation","FireComplianceUK","Bankole & Associates","TradeCompare","TripleMMM"];

export default function ContentBank(){
 const [brand,setBrand]=useState("Bubble Leisure");
 const [objective,setObjective]=useState("Create content that grows the audience and produces measurable commercial results.");
 const [count,setCount]=useState(10);
 const [generation,setGeneration]=useState<Generation|null>(null);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState<string|null>(null);
 const [status,setStatus]=useState<Record<number,string>>({});
 const pieces=useMemo(()=>generation?.pieces??[],[generation]);

 const generate=async()=>{
  setBusy(true);setError(null);setGeneration(null);setStatus({});
  try{
   const response=await fetch("/api/content-bank/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brand,objective,count})});
   const data=await response.json() as {generation?:Generation;error?:string};
   if(!response.ok||!data.generation) throw new Error(data.error??"Content generation failed.");
   setGeneration(data.generation);
  }catch(cause){setError(cause instanceof Error?cause.message:"Content generation failed.");}
  finally{setBusy(false);}
 };
 const copy=(x:GeneratedPiece)=>navigator.clipboard?.writeText(`${x.hook}\n\n${x.caption}\n\nCTA: ${x.cta}\n\nPRODUCTION: ${x.productionBrief}`);

 return <><section className="exec-hero"><div><p className="eyebrow">CONTENT BANK · SKILL-LED GENERATION</p><h2>Generate content from your approved Skills—not generic templates.</h2><p>Choose the business and objective. HQ selects the venture's preferred approved Skills, uses their actual SKILL.md instructions and returns distinct production-ready concepts. Nothing is pre-filled just to make the bank look busy.</p></div><strong>{pieces.length} evidence-led pieces</strong></section>
 <section className="panel wide"><div className="panel-title"><h2>Generate a content batch</h2><span>Skills → strategy → content</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}>
 <label>Business<select value={brand} onChange={e=>setBrand(e.target.value)}>{brands.map(x=><option key={x}>{x}</option>)}</select></label>
 <label>Pieces<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[5,10,20,50,100].map(x=><option key={x}>{x}</option>)}</select></label>
 </div><label style={{display:"block",marginTop:12}}>What do you want the content to achieve?<textarea value={objective} onChange={e=>setObjective(e.target.value)} rows={3} style={{width:"100%"}}/></label>
 <div className="output-actions"><button className="primary" onClick={generate} disabled={busy||!objective.trim()}>{busy?"Running approved Skills…":`Generate ${count} with my Skills →`}</button></div>
 <p className="note">HQ will refuse to fake research. If approved Skills, the database or AI execution are not configured, it will tell you exactly what is missing instead of substituting generic posts.</p></section>
 {error&&<section className="creative-error">{error}</section>}
 {generation&&<section className="panel wide"><div className="panel-title"><h2>{generation.brand} strategy</h2><span>{generation.skillsUsed.length} Skills used</span></div><p><b>Objective · </b>{generation.objective}</p><p>{generation.strategy}</p><details><summary>Why HQ generated this batch</summary><p>{generation.evidenceSummary}</p><p><b>Skills · </b>{generation.skillsUsed.join(" · ")}</p></details></section>}
 {pieces.length>0&&<section className="panel wide"><div style={{display:"grid",gap:12}}>{pieces.map((x,i)=><article key={i} style={{border:"1px solid rgba(255,255,255,.12)",borderRadius:14,padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><span className="mono">{generation?.brand} · #{i+1} · {x.format}</span><span className="badge needs-approval">{status[i]||"GENERATED BY SKILLS"}</span></div><h3 style={{margin:"10px 0 6px"}}>{x.title}</h3><p><b>Purpose · </b>{x.purpose}</p><p><b>Hook · </b>{x.hook}</p><p>{x.concept}</p><p>{x.caption}</p><p><b>CTA · </b>{x.cta}</p><details><summary>Production brief + provenance</summary><p>{x.productionBrief}</p><p><b>Skills used · </b>{x.skillsUsed?.join(" · ")||generation?.skillsUsed.join(" · ")}</p>{x.evidenceUsed?.length?<p><b>Evidence · </b>{x.evidenceUsed.join(" · ")}</p>:null}</details><div className="output-actions"><button onClick={()=>copy(x)}>Copy ready post</button><button onClick={()=>setStatus(s=>({...s,[i]:"SHORTLISTED"}))}>Shortlist</button><button onClick={()=>setStatus(s=>({...s,[i]:"IN PRODUCTION"}))}>Move to production</button><button onClick={()=>setStatus(s=>({...s,[i]:"POSTED"}))}>Mark posted</button></div></article>)}</div></section>}
 </>;
}