"use client";
import { useMemo, useState } from "react";
type Brand={name:string;audience:string;offer:string;cta:string;proof:string;themes:string[]};
const brands:Brand[]=[
{name:"Bubble Leisure",audience:"parents, schools and groups planning active events",offer:"Bubble Football, Nerf, Dodgeball, Archery and Axe Throwing experiences",cta:"DM PARTY with your date, postcode and group size.",proof:"simple organised sessions that keep groups active",themes:["party stress","kids energy","parent convenience","school enrichment","group competition","birthday memories","activity choice","venue flexibility","behind the scenes","booking confidence"]},
{name:"SAYAH",audience:"R&B and rap listeners discovering a new artist",offer:"songs, visual storytelling and the worlds around X2Z, Bad Example and Mind Yours",cta:"Follow SAYAH and tell me which line stayed with you.",proof:"music-led storytelling with a distinct visual identity",themes:["unreleased lyric","late-night thought","studio moment","song story","visual world","fan question","R&B mood","rap bars","project lore","artist personality"]},
{name:"Lucky Studios",audience:"artists and brands that need distinctive AI-native creative",offer:"artist management, visual campaigns, AI music visuals and cinematic content",cta:"DM LUCKY with the campaign you want to bring to life.",proof:"creative direction that connects concept, music and visual execution",themes:["creative direction","AI workflow","campaign concept","visual identity","artist development","before and after","production process","brand world","music marketing","creative experiment"]},
{name:"Brilliant AI Automation",audience:"business owners losing time and revenue to manual work",offer:"practical AI automation that connects tools, workflows and commercial goals",cta:"DM AUTOMATE with the process wasting the most time.",proof:"automation designed around measurable business outcomes",themes:["manual admin","lead response","sales follow-up","customer service","reporting","data entry","handoffs","AI workforce","workflow audit","ROI"]},
{name:"FireComplianceUK",audience:"property managers, care homes, housing providers, schools and FM teams",offer:"fire-compliance opportunity matching, specialist suppliers and bid support",cta:"DM FIRE with your property portfolio or requirement.",proof:"specialist matching and clearer routes from requirement to delivery",themes:["fire doors","inspection readiness","compliance planning","supplier matching","tender readiness","care homes","housing","schools","FM teams","documentation"]},
{name:"Bankole & Associates",audience:"business owners and project sponsors seeking credible capital introductions",offer:"capital advisory, investor introductions and transaction coordination",cta:"DM CAPITAL with the project, raise size and current stage.",proof:"structured preparation before introductions and funding conversations",themes:["investment readiness","deal preparation","capital stack","investor fit","due diligence","term sheets","mandates","project finance","deal room","funding mistakes"]},
{name:"TradeCompare",audience:"tradespeople and buyers who want to make better purchasing decisions",offer:"comparison intelligence for trade products, prices and buying decisions",cta:"Follow TradeCompare for smarter trade buying decisions.",proof:"decision support built around price, value and practical trade needs",themes:["price comparison","true cost","product choice","trade margins","supplier differences","buying mistakes","market movement","tool choice","materials","deal spotting"]},
{name:"TripleMMM",audience:"founders and leaders with stories worth documenting",offer:"cinematic founder interviews and story-led business content",cta:"DM STORY if your journey deserves more than a generic interview.",proof:"interviews built around decisions, tension and useful lessons",themes:["founder decision","turning point","failure lesson","origin story","trade-off","leadership","behind the business","hard question","growth lesson","legacy"]}
];
const formats=["Reel","Carousel","Founder POV","Story","Photo post","Talking-head video","Mini case study","Myth-buster","Behind-the-scenes","Question post"];
const angles=["Pattern interrupt","Contrarian","How-to","Mistake","Before/after","Checklist","Story","Proof","FAQ","Opinion prompt"];
function build(b:Brand,i:number){const t=b.themes[i%10],f=formats[Math.floor(i/10)%10],a=angles[(i+Math.floor(i/10))%10];const hooks=["The part nobody tells you about "+t+".","Before you spend another pound on "+t+", check this.","Most people approach "+t+" backwards.","Three things to know about "+t+" before you start.","What good "+t+" actually looks like.","A small change in "+t+" can change the whole outcome.","Here's the decision behind our approach to "+t+".","If "+t+" matters to you, measure this—not vanity metrics.","The most common question we get about "+t+".","Would you choose speed, price or quality for "+t+"?"];const body=hooks[i%10]+" For "+b.audience+", the goal is not more noise; it is a clearer decision. We focus on "+b.offer+". The useful test is whether it creates "+b.proof+". "+(i%3===0?"Save this as a checklist for the next time the decision comes up.":i%3===1?"Share this with the person who normally owns this decision.":"Comment with the part you want us to break down next.");const brief=f+" · "+a+". Open on “"+hooks[i%10]+"” Show one concrete example of "+t+", then one proof/detail shot, then a clean end frame. Keep the first 2 seconds visually active; avoid stock-looking imagery and overcrowded text.";return {id:b.name+"-"+(i+1),brand:b.name,n:i+1,theme:t,format:f,angle:a,hook:hooks[i%10],caption:body,cta:b.cta,brief};}
const all=brands.flatMap(b=>Array.from({length:100},(_,i)=>build(b,i)));
export default function ContentBank(){const [brand,setBrand]=useState("All brands"),[format,setFormat]=useState("All formats"),[q,setQ]=useState(""),[status,setStatus]=useState<Record<string,string>>({});const rows=useMemo(()=>all.filter(x=>(brand==="All brands"||x.brand===brand)&&(format==="All formats"||x.format===format)&&(!q||JSON.stringify(x).toLowerCase().includes(q.toLowerCase()))),[brand,format,q]);const copy=(x:(typeof all)[number])=>navigator.clipboard?.writeText(x.hook+"\n\n"+x.caption+"\n\nCTA: "+x.cta+"\n\nPRODUCTION: "+x.brief);return <><section className="exec-hero"><div><p className="eyebrow">SOCIAL CONTENT ENGINE · 800 READY IDEAS</p><h2>100 usable content pieces for every active brand.</h2><p>Filter a brand, pick a piece, copy it or move it into production. This is a working content bank—not placeholder cards.</p></div><strong>{rows.length} pieces shown</strong></section><section className="panel wide"><div style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:16}}><select value={brand} onChange={e=>setBrand(e.target.value)}><option>All brands</option>{brands.map(b=><option key={b.name}>{b.name}</option>)}</select><select value={format} onChange={e=>setFormat(e.target.value)}><option>All formats</option>{formats.map(x=><option key={x}>{x}</option>)}</select><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search themes, hooks, formats…" style={{minWidth:260}}/></div><div style={{display:"grid",gap:12}}>{rows.map(x=><article key={x.id} style={{border:"1px solid rgba(255,255,255,.12)",borderRadius:14,padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><span className="mono">{x.brand} · #{x.n} · {x.format} · {x.angle}</span><span className="badge needs-approval">{status[x.id]||"READY"}</span></div><h3 style={{margin:"10px 0 6px"}}>{x.hook}</h3><p>{x.caption}</p><p><b>CTA · </b>{x.cta}</p><details><summary>Production brief</summary><p>{x.brief}</p></details><div className="output-actions"><button onClick={()=>copy(x)}>Copy ready post</button><button onClick={()=>setStatus(s=>({...s,[x.id]:"SHORTLISTED"}))}>Shortlist</button><button onClick={()=>setStatus(s=>({...s,[x.id]:"IN PRODUCTION"}))}>Move to production</button><button onClick={()=>setStatus(s=>({...s,[x.id]:"POSTED"}))}>Mark posted</button></div></article>)}</div></section></>;}
