"use client";

import { useMemo, useState } from "react";
import { aiJobs, leads, pricingRules as seededRules, skills, venues, ventures } from "@/lib/demo-data";
import { PricingRule } from "@/lib/types";

const nav = ["Command Centre", "Ventures", "Bubble Operations", "Contacts & Orgs", "Revenue Pipeline", "Tasks", "AI Jobs", "Skills Library", "Documents", "Revenue"];
const money = (n: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(n);

export default function HQApp() {
  const [view, setView] = useState("Command Centre");
  const [rules, setRules] = useState<PricingRule[]>(seededRules);
  const [selectedRule, setSelectedRule] = useState("combo-90");
  const [venueCost, setVenueCost] = useState(85);
  const [travel, setTravel] = useState(24);
  const [openCall, setOpenCall] = useState<string | null>(null);
  const [callResult, setCallResult] = useState("No outcome recorded");
  const rule = rules.find(r => r.id === selectedRule) ?? rules[0];
  const calculation = useMemo(() => {
    const base = Math.max(rule.min, (rule.min + rule.max) / 2);
    const direct = rule.staffing + rule.equipment + venueCost + travel;
    const marginFloor = direct / (1 - rule.minMargin / 100);
    const customer = Math.ceil(Math.max(base, marginFloor) / 5) * 5;
    return { direct, customer, profit: customer - direct, margin: Math.round(((customer - direct) / customer) * 100) };
  }, [rule, venueCost, travel]);
  const toggleRule = (id: string) => setRules(prev => prev.map(r => r.id === id ? { ...r, active: !r.active } : r));

  return <main className="shell">
    <aside className="sidebar"><div className="brand"><span className="key">◆</span> BANKOLE <b>HQ</b></div><p className="private">PRIVATE OPERATING SYSTEM</p>
      <nav>{nav.map(item => <button className={view === item ? "nav active" : "nav"} onClick={() => setView(item)} key={item}>{item}</button>)}</nav>
      <div className="side-foot"><span className="pulse"/>System ready<br/><small>Demo workspace · V0.1</small></div>
    </aside>
    <section className="content"><header><div><p className="eyebrow">TUESDAY, 16 SEPTEMBER</p><h1>{view}</h1></div><div className="header-actions"><button className="quiet">⌘ K Search</button><button className="avatar">TB</button></div></header>
      {view === "Command Centre" && <CommandCentre setView={setView}/>} 
      {view === "Ventures" && <Ventures/>}
      {view === "Bubble Operations" && <BubbleOps openCall={openCall} setOpenCall={setOpenCall} callResult={callResult} setCallResult={setCallResult}/>} 
      {view === "Revenue Pipeline" && <Pipeline/>}
      {view === "Tasks" && <Tasks/>}
      {view === "AI Jobs" && <AiJobs/>}
      {view === "Skills Library" && <Skills/>}
      {view === "Contacts & Orgs" && <Contacts/>}
      {view === "Documents" && <Documents/>}
      {view === "Revenue" && <Revenue/>}
      {view === "Bubble Operations" && <section className="split lower"><PricingEngine rules={rules} rule={rule} selectRule={setSelectedRule} venueCost={venueCost} setVenueCost={setVenueCost} travel={travel} setTravel={setTravel} calc={calculation}/><PricingRules rules={rules} toggle={toggleRule}/></section>}
    </section>
  </main>;
}

function CommandCentre({setView}:{setView:(v:string)=>void}) { return <><section className="metric-grid"><Metric label="Pipeline at risk" value="£1,075" hint="2 actions overdue" tone="orange"/><Metric label="Hot opportunities" value="2" hint="£1,075 potential value" tone="lime"/><Metric label="AI approvals" value="1" hint="Venue ranking ready" tone="purple"/><Metric label="Cash received" value="£2,480" hint="This month · all ventures" tone="blue"/></section><section className="split"><div className="panel attention"><PanelTitle title="Needs your attention" action="View all"/><Attention title="Approve venue shortlist" body="Amelia Carter · Colchester birthday party" badge="AI approval" onClick={()=>setView("AI Jobs")}/><Attention title="Call Jake Wilson" body="Adult bubble football · asked for a callback" badge="Call today" onClick={()=>setView("Bubble Operations")}/><Attention title="Chase Maya's quote" body="No reply for 48 hours · £250 potential" badge="Overdue" onClick={()=>setView("Bubble Operations")}/></div><div className="panel"><PanelTitle title="Revenue pipeline" action="Open pipeline"/><div className="funnel"><div style={{width:"100%"}}>New & requirements <b>£1,325</b></div><div style={{width:"82%"}}>Venue & pricing <b>£1,075</b></div><div style={{width:"58%"}}>Quote & follow-up <b>£250</b></div></div><p className="note">Focus first on the school quote and Colchester venue approval.</p></div></section><section className="panel wide"><PanelTitle title="Live AI workflow" action="Open AI jobs"/><div className="workflow"><span>Lead received</span><i/> <span>Requirements extracted</span><i/> <span className="current">Venue ranking needs approval</span><i/> <span>Quote draft</span></div><p className="note">No external agent is connected in V0.1. These are persisted workflow states ready for a server-side integration.</p></section></> }
function Metric({label,value,hint,tone}:{label:string;value:string;hint:string;tone:string}) {return <div className="metric"><span className={'dot '+tone}/><p>{label}</p><strong>{value}</strong><small>{hint}</small></div>}
function PanelTitle({title,action}:{title:string;action:string}) {return <div className="panel-title"><h2>{title}</h2><button>{action} →</button></div>}
function Attention({title,body,badge,onClick}:{title:string;body:string;badge:string;onClick:()=>void}) {return <button className="attention-row" onClick={onClick}><span className="warning">!</span><span><b>{title}</b><small>{body}</small></span><em>{badge}</em><span>›</span></button>}
function Ventures(){return <section className="cards">{ventures.map(v=><article className="venture" key={v[0]}><span className="mono">{v[1]}</span><h2>{v[0]}</h2><p><span className="status"/> {v[2]}</p><footer>{v[3]} <b>→</b></footer></article>)}</section>}
function BubbleOps({openCall,setOpenCall,callResult,setCallResult}:{openCall:string|null;setOpenCall:(x:string|null)=>void;callResult:string;setCallResult:(x:string)=>void}) {return <><section className="bubble-head"><div><p className="eyebrow">BUBBLE LEISURE · OPERATING WORKFLOW</p><h2>From lead to profitable event.</h2><p>Every quote is costed against an editable rule and venue-price confidence is explicit.</p></div><button className="primary">+ New lead</button></section><section className="kanban">{["New lead","Venue sourcing","Pricing","Call","Follow-up"].map(stage=><div className="kanban-col" key={stage}><h3>{stage}</h3>{leads.filter(l=>l.stage===stage).map(l=><article className="lead" key={l.name}><span className="tag">{l.flag}</span><h4>{l.name}</h4><p>{l.event}</p><small>⌖ {l.location}</small><footer><b>{money(l.value)}</b>{l.stage === "Call" ? <button onClick={()=>setOpenCall(l.name)}>Call now</button> : <button>Open →</button>}</footer></article>)}</div>)}</section><section className="panel venue-panel"><PanelTitle title="Venue Engine · known venue shortlist" action="Open all venues"/><table><thead><tr><th>Venue</th><th>Fit</th><th>Price</th><th>Confidence</th><th>Availability</th></tr></thead><tbody>{venues.map(v=><tr key={v.name}><td><b>{v.name}</b><small>{v.postcode} · {v.contact}</small></td><td>{v.activities}<small>Capacity {v.capacity}</small></td><td>{money(v.price)}<small>{v.unit}</small></td><td><span className={'badge '+v.status.toLowerCase()}>{v.status}</span><small>{v.status === "Estimated" ? "Must not be quoted as verified" : v.verified}</small></td><td>{v.availability}<small>{v.method}</small></td></tr>)}</tbody></table><p className="note">Integration boundary: a future Venue Agent receives postcode, date, activities, group size and budget; it returns sources, availability evidence and ranked venue candidates. It does not mark a cost Verified without evidence.</p></section>{openCall && <div className="modal"><section><button className="close" onClick={()=>setOpenCall(null)}>×</button><p className="eyebrow">SOFTPHONE INTEGRATION BOUNDARY</p><h2>Call {openCall}</h2><p>This browser dialler is intentionally disconnected until a Twilio (or equivalent) server-side integration is configured. The outcome can still be recorded.</p><div className="outcomes">{["Callback","No answer","Quote","Booked","Lost"].map(x=><button key={x} onClick={()=>setCallResult(x)} className={callResult===x?"chosen":""}>{x}</button>)}</div><p className="call-result">Current outcome: <b>{callResult}</b></p><button className="primary" onClick={()=>setOpenCall(null)}>Save call outcome</button></section></div>}</>}
function PricingEngine({rules,rule,selectRule,venueCost,setVenueCost,travel,setTravel,calc}:{rules:PricingRule[];rule:PricingRule;selectRule:(x:string)=>void;venueCost:number;setVenueCost:(x:number)=>void;travel:number;setTravel:(x:number)=>void;calc:{direct:number;customer:number;profit:number;margin:number}}){return <section className="panel calculator"><PanelTitle title="Pricing Engine" action="Rules are editable"/><label>Base rule<select value={rule.id} onChange={e=>selectRule(e.target.value)}>{rules.filter(r=>r.active).map(r=><option key={r.id} value={r.id}>{r.name} · {r.activity}</option>)}</select></label><div className="field-grid"><label>Venue cost<input type="number" value={venueCost} onChange={e=>setVenueCost(Number(e.target.value))}/></label><label>Travel<input type="number" value={travel} onChange={e=>setTravel(Number(e.target.value))}/></label></div><div className="price-result"><div><span>Customer price</span><b>{money(calc.customer)}</b></div><div><span>Direct costs</span><b>{money(calc.direct)}</b></div><div><span>Est. gross profit</span><b className="profit">{money(calc.profit)} · {calc.margin}%</b></div></div><p className="note">Rule baseline {money(rule.min)}–{money(rule.max)} · min margin {rule.minMargin}% · staffing and equipment are included in direct costs.</p></section>}
function PricingRules({rules,toggle}:{rules:PricingRule[];toggle:(x:string)=>void}){return <section className="panel rules"><PanelTitle title="Admin · Pricing rules" action="+ Add rule"/><div className="rules-list">{rules.map(r=><div key={r.id}><span><b>{r.name}</b><small>{r.customerType} · {r.duration} min · {r.activity}</small></span><span><b>{money(r.min)}{r.max!==r.min?`–${money(r.max)}`:""}</b><button className={r.active?"switch on":"switch"} onClick={()=>toggle(r.id)} aria-label="toggle rule"/></span></div>)}</div></section>}
function Pipeline(){return <section className="panel venue-panel"><PanelTitle title="Revenue pipeline" action="+ Opportunity"/><table><thead><tr><th>Customer</th><th>Requirements</th><th>Stage</th><th>Potential</th><th>Next action</th></tr></thead><tbody>{leads.map(l=><tr key={l.name}><td><b>{l.name}</b><small>{l.location}</small></td><td>{l.event}</td><td><span className="badge verified">{l.stage}</span></td><td><b>{money(l.value)}</b></td><td>{l.next}</td></tr>)}</tbody></table></section>}
function Tasks(){return <section className="panel"><PanelTitle title="Priority queue" action="+ Task"/>{["Approve Colchester venue ranking","Call Jake Wilson by 4pm","Follow up Maya quote","Confirm school pricing rule"].map((x,i)=><div className="task" key={x}><span className={i<2?"check urgent":"check"}/><b>{x}</b><small>{i<2?"Due today":"Bubble Leisure"}</small></div>)}</section>}
function AiJobs(){return <section className="panel venue-panel"><PanelTitle title="AI job queue" action="+ New job"/><table><thead><tr><th>Job</th><th>Venture</th><th>Skill</th><th>Status</th><th>Updated</th></tr></thead><tbody>{aiJobs.map(j=><tr key={j.title}><td><b>{j.title}</b><small>Input/output retained when connected</small></td><td>{j.venture}</td><td>{j.skill}</td><td><span className={'badge '+j.status.toLowerCase().replaceAll(" ","-")}>{j.status}</span></td><td>{j.updated}</td></tr>)}</tbody></table><p className="note">State model: Queued → Running → Needs Approval → Completed. Failed and Blocked require a human decision; jobs will execute only through a server-side provider adapter.</p></section>}
function Skills(){return <section className="cards skills">{skills.map(s=><article className="venture" key={s}><span className="mono">GOOGLE DRIVE PLACEHOLDER</span><h2>{s}</h2><p>Not connected</p><footer>Awaiting source file <b>→</b></footer></article>)}</section>}
function Contacts(){return <section className="panel"><PanelTitle title="Contacts & organisations" action="+ Contact"/><div className="empty">No imported contacts yet. Use this area for customers, venue managers, suppliers, partners and investors; links to ventures and deals are relational in the database schema.</div></section>}
function Documents(){return <section className="panel"><PanelTitle title="Documents" action="+ Upload"/><div className="empty">Document storage is ready in the data model. Connect Google Drive or secure object storage later; no Drive files were invented or copied into V0.1.</div></section>}
function Revenue(){return <><section className="metric-grid"><Metric label="Received this month" value="£2,480" hint="Demonstration data" tone="lime"/><Metric label="Expected pipeline" value="£2,650" hint="Open opportunities" tone="blue"/><Metric label="Estimated gross profit" value="£1,228" hint="Quoted Bubble work" tone="purple"/></section><section className="panel"><PanelTitle title="Revenue tracking" action="+ Entry"/><div className="empty">Revenue entries will be stored per venture, separated into income and direct costs. Demonstration figures are shown until a database is connected.</div></section></>}
