"use client";

import { useEffect, useMemo, useState } from "react";

type Competitor = { id: string; name: string; websiteUrl?: string | null; lastCollectedAt?: string | null; lastCollectionError?: string | null };
type Evidence = { id: string; competitorName: string; platform: string; distribution: string; title: string; sourceUrl?: string | null; mediaUrl?: string | null; contentText?: string | null; activityStatus?: string | null; capturedAt: string; provenance: string };
type Opportunity = { id: string; title: string; brief: string; status: string; createdAt: string };
type SkillRun = { id: string; output: string; evidence: Array<{ id: string; title: string; sourceUrl?: string | null; provenance: string }> };
type ImportedSkill = { id: string; name: string; active: boolean };

const tabs = ["Competitor Overview", "Paid Ads", "Organic Content", "Top Creatives", "Repeated / Long-running", "Hooks", "Offers", "Formats", "Emerging Themes", "Recent Changes", "Content Gaps", "Opportunities"];

export default function IntelligenceStudio({ setView }: { setView: (view: string) => void }) {
  const ventureOptions=["Bubble Leisure","Brilliant AI Automation","FireComplianceUK","Bankole & Associates","TradeCompare","Lucky Studios","SAYAH","Oddly","TripleMMM"];\n  const [venture,setVenture]=useState("Bubble Leisure");\n  const [ventureId,setVentureId]=useState("");
  const [tab, setTab] = useState("Competitor Overview");
  const [competitors, setCompetitors] = useState<Competitor[]>([]);
  const [evidence, setEvidence] = useState<Evidence[]>([]);
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]);
  const [skills, setSkills] = useState<ImportedSkill[]>([]);
  const [selected, setSelected] = useState<string[]>([]);
  const [skill, setSkill] = useState("Niche Hacking");
  const [scope, setScope] = useState("one creative");
  const [result, setResult] = useState<SkillRun | null>(null);
  const [newCompetitor, setNewCompetitor] = useState({ name: "Bubble Boy Events", websiteUrl: "https://www.bubbleboyevents.co.uk/" });
  const [capture, setCapture] = useState({ url: "", note: "", interaction: "SAVED", distribution: "ORGANIC" });
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = async () => {
    setError(null);
    const response = await fetch(`/api/intelligence/competitors?venture=${encodeURIComponent(venture)}`, { cache: "no-store" });
    const data = await response.json() as { ventureId?: string; competitors?: Competitor[]; evidence?: Evidence[]; opportunities?: Opportunity[]; error?: string };
    if (!response.ok) { setError(data.error ?? "Competitor Intelligence could not load."); return; }
    setVentureId(data.ventureId ?? ""); setCompetitors(data.competitors ?? []); setEvidence(data.evidence ?? []); setOpportunities(data.opportunities ?? []);
    const skillResponse = await fetch("/api/skills", { cache: "no-store" });
    if (skillResponse.ok) { const skillData = await skillResponse.json() as { skills?: ImportedSkill[] }; setSkills(skillData.skills ?? []); }
  };
  useEffect(() => { void load(); }, [venture]);
  const filtered = useMemo(() => evidence.filter(item => tab === "Paid Ads" ? item.distribution === "PAID" : tab === "Organic Content" ? item.distribution === "ORGANIC" : true), [evidence, tab]);
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  const captureSocial = async () => {
    setBusy("capture"); setError(null); setNotice(null);
    try {
      const response = await fetch("/api/intelligence/capture", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ venture, ...capture }) });
      const responseText = await response.text();
      let data: { evidence?: Evidence; notice?: string; error?: string };
      try { data = JSON.parse(responseText) as typeof data; } catch { throw new Error(responseText.slice(0, 300) || `Capture failed (${response.status}).`); }
      if (!response.ok || !data.evidence) throw new Error(data.error ?? "Public social source could not be captured.");
      setCapture(current => ({ ...current, url: "", note: "" }));
      setNotice(data.notice ?? "Public source captured.");
      await load();
      setSelected(current => data.evidence ? [...new Set([...current, data.evidence.id])] : current);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Public social source could not be captured."); }
    finally { setBusy(null); }
  };
  const addCompetitor = async () => { setBusy("add"); setError(null); try { const response = await fetch("/api/intelligence/competitors", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ venture, ...newCompetitor }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "Competitor could not be saved."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Competitor could not be saved."); } finally { setBusy(null); } };
  const collect = async (competitor: Competitor) => { setBusy(competitor.id); setError(null); try { const response = await fetch(`/api/intelligence/competitors/${competitor.id}/collect`, { method: "POST" }); const data = await response.json() as { error?: string; notice?: string }; if (!response.ok) throw new Error(data.error ?? "Collection failed."); if (data.notice) setError(data.notice); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Collection failed."); } finally { setBusy(null); } };
  const addStarters = async () => { setBusy("starters"); setError(null); try { const response = await fetch("/api/intelligence/competitors/starter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ venture }) }); const data = await response.json() as { error?: string; notice?: string }; if (!response.ok) throw new Error(data.error ?? "Public sources could not be added."); setError(data.notice ?? null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Public sources could not be added."); } finally { setBusy(null); } };
  const collectAll = async () => { setBusy("all"); setError(null); try { for (const competitor of competitors) await collect(competitor); } finally { setBusy(null); } };
  const runSkill = async () => { setBusy("skill"); setError(null); setResult(null); try { const response = await fetch("/api/intelligence/run-skill", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ventureId, skillName: skill, evidenceIds: selected, scope: { mode: scope, source: "Competitor Intelligence" } }) }); const data = await response.json() as { run?: SkillRun; error?: string }; if (!response.ok || !data.run) throw new Error(data.error ?? "Approved skill did not run."); setResult(data.run); } catch (cause) { setError(cause instanceof Error ? cause.message : "Approved skill did not run."); } finally { setBusy(null); } };
  const saveOpportunity = async () => { if (!result) return; setBusy("opportunity"); setError(null); try { const response = await fetch("/api/intelligence/opportunities", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ venture, title: `${skill} opportunity`, brief: result.output, evidenceId: selected[0], skillRunId: result.id }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "Opportunity could not be saved."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Opportunity could not be saved."); } finally { setBusy(null); } };
  const sendToCreate = (brief: string, title: string, sources: string) => { sessionStorage.setItem("bankole-hq:create-handoff", JSON.stringify({ venture, project: title, skill: result ? skill : "Observed intelligence", output: brief, sourceEvidence: sources })); setView("Create"); };
  const sendToAskHQ = () => {
    const sources = evidence.filter(item => selected.includes(item.id));
    sessionStorage.setItem("bankole-hq:workflow-handoff", JSON.stringify({
      venture,
      sourceEvidenceIds: selected,
      sourceContext: sources.map(item => `[${item.id}] ${item.title}\n${item.contentText ?? ""}\nSource: ${item.sourceUrl ?? "Not captured"}\nProvenance: ${item.provenance}`).join("\n\n"),
      outcome: `Find me new ${venture} opportunities from the selected competitor intelligence`,
    }));
    setView("Ask HQ");
  };

  const approvedSkills = skills.filter((item) => item.active);
  return <>
    <section className="exec-hero intelligence-hero"><div><p className="eyebrow">{venture.toUpperCase()} · COMPETITOR INTELLIGENCE</p><h2>Collect observable evidence. Use approved skills to find differentiated opportunities.</h2><p>Paid and organic activity are separate. No private performance, conversion or ROAS is invented.</p></div><div className="output-actions"><button onClick={addStarters} disabled={!!busy}>{busy === "starters" ? "Adding sources…" : "Add public starter sources"}</button><button className="primary" onClick={() => void load()} disabled={!!busy}>Refresh workspace</button></div></section>
    <section className="panel wide"><div className="panel-title"><h2>Venture intelligence workspace</h2><span>Real evidence · approved skills</span></div><label>Venture<select value={venture} onChange={e=>{setVenture(e.target.value);setSelected([]);setResult(null)}}>{ventureOptions.map(v=><option key={v}>{v}</option>)}</select></label></section><section className="intelligence-loop"><span>Research / collect</span><i/><span className="current">Approved skill</span><i/><span>Evidence-backed opportunity</span><i/><span>Send to Create</span><i/><span>Test / learn</span></section>
    <nav className="intel-tabs">{tabs.map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
    <section className="panel research-inbox"><div className="research-heading"><div><p className="section-kicker">STEP 1 · CAPTURE INSPIRATION</p><h2>Add something you saw on social media</h2><p>Paste one public post or video. Tell HQ what caught your attention so your approved skills can use both the source and your judgement.</p></div><span className="source-pill">Collected securely with ScraperAPI</span></div><div className="research-grid"><label className="research-field research-url"><span>Public post or video link</span><input value={capture.url} onChange={event => setCapture({ ...capture, url: event.target.value })} placeholder="Paste an Instagram, Facebook, YouTube or TikTok link"/></label><label className="research-field"><span>Your interaction</span><select value={capture.interaction} onChange={event => setCapture({ ...capture, interaction: event.target.value })}><option value="SAVED">I saved it</option><option value="LIKED">I liked it</option><option value="SAW">I noticed it</option><option value="COMPETITOR">Competitor research</option></select></label><label className="research-field"><span>Content source</span><select value={capture.distribution} onChange={event => setCapture({ ...capture, distribution: event.target.value })}><option value="ORGANIC">Organic content</option><option value="PAID">Paid advertisement</option></select></label><label className="research-field research-note"><span>What caught your attention?</span><textarea rows={4} value={capture.note} onChange={event => setCapture({ ...capture, note: event.target.value })} placeholder="Example: The first-second hook, genuine parent reaction and quick pacing would suit a Bubble Leisure ad."/></label></div><div className="research-footer"><div><button className="primary capture-button" onClick={captureSocial} disabled={!!busy || !capture.url.trim()}>{busy === "capture" ? "Collecting public evidence…" : "Capture this content →"}</button><small>Only the link you paste is collected. HQ cannot read your private Saved or Likes folders.</small></div><div className="next-step"><b>What happens next?</b><span>The captured item appears in Evidence below, already selected and ready for Run Skill or Ask HQ.</span></div></div>{notice && <div className="capture-success">{notice}</div>}</section>
    <section className="intelligence-workspace"><section className="panel intelligence-controls"><div className="panel-title"><div><p className="section-kicker">STEP 2A · MONITOR SOURCES</p><h2>Competitors</h2></div><span>Public sources only</span></div><label>Competitor name<input value={newCompetitor.name} onChange={event => setNewCompetitor({ ...newCompetitor, name: event.target.value })}/></label><label>Public website URL<input value={newCompetitor.websiteUrl} onChange={event => setNewCompetitor({ ...newCompetitor, websiteUrl: event.target.value })}/></label><button className="primary" onClick={addCompetitor} disabled={!!busy}>{busy === "add" ? "Saving…" : "Save competitor"}</button><p className="note">The starter list saves only public website sources. Add a specific public social, YouTube or Meta Ad Library URL to a competitor record before its dedicated collector is enabled.</p>{competitors.length > 1 && <button onClick={collectAll} disabled={!!busy}>{busy === "all" ? "Collecting public sources…" : "Collect all public websites"}</button>}{competitors.map(item => <article className="competitor-row" key={item.id}><b>{item.name}</b><small>{item.lastCollectedAt ? `Collected ${new Date(item.lastCollectedAt).toLocaleString()}` : "Not collected"}</small>{item.lastCollectionError && <small className="error-text">{item.lastCollectionError}</small>}<button onClick={() => collect(item)} disabled={!!busy}>{busy === item.id ? "Collecting…" : "Collect website"}</button></article>)}</section>
      <section className="panel evidence-panel"><div className="panel-title"><div><p className="section-kicker">STEP 2B · SELECT EVIDENCE</p><h2>{tab}</h2></div><span>{filtered.length} observed records</span></div>{filtered.length === 0 ? <div className="create-empty">No observed records yet. Save a competitor and collect a publicly accessible source. This workspace does not populate itself with invented claims.</div> : filtered.map(item => <article key={item.id} className="evidence-card"><label className="evidence-select"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)}/><span><b>{item.title}</b><small>{item.competitorName} · {item.platform} · {item.distribution}</small></span></label>{item.mediaUrl && <img className="evidence-media" src={item.mediaUrl} alt="Observed competitor creative"/>}<p>{item.contentText}</p><div className="evidence-fields"><span><b>Observed</b>{item.activityStatus ?? "Captured"}</span><span><b>Source</b>{item.sourceUrl ? <a href={item.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a> : "Not available"}</span><span><b>Collected</b>{new Date(item.capturedAt).toLocaleString()}</span><span><b>AI / skill inference</b>None until an approved skill runs</span></div><footer><small>{item.provenance}</small></footer></article>)}</section></section>
    <section className="panel skill-runner"><div className="panel-title"><div><p className="section-kicker">STEP 3 · ANALYSE AND CREATE</p><h2>Use your approved Skills</h2></div><span>{selected.length} selected evidence item{selected.length === 1 ? "" : "s"}</span></div><div className="skill-controls"><label>Scope<select value={scope} onChange={event => setScope(event.target.value)}>{["one creative", "one competitor", "several competitors", "campaign", "platform", "selected date range"].map(item => <option key={item}>{item}</option>)}</select></label><label>Approved SKILL.md<select value={skill} onChange={event => setSkill(event.target.value)} disabled={!approvedSkills.length}>{approvedSkills.length ? approvedSkills.map(item => <option key={item.id}>{item.name}</option>) : <option>Import and approve a skill first</option>}</select></label><button className="primary" onClick={runSkill} disabled={busy === "skill" || !selected.length || !approvedSkills.length}>{busy === "skill" ? "Running approved skill…" : "Run Skill"}</button><button onClick={sendToAskHQ} disabled={!selected.length}>Ask HQ to build workflow →</button></div><p className="note">{approvedSkills.length ? "The application reads actual stored SKILL.md instructions only. It does not create a generic replacement methodology." : "Go to Skills Library → Import actual Drive skills → approve the workflow you want to run."}</p></section>
    {result && <section className="panel intelligence-result"><div className="panel-title"><h2>{skill} output</h2><span className="badge needs-approval">Evidence-linked</span></div><pre>{result.output}</pre><div className="evidence-links"><b>Source evidence</b>{result.evidence.map(item => <span key={item.id}>{item.title} · {item.provenance}</span>)}</div><div className="output-actions"><button onClick={() => navigator.clipboard?.writeText(result.output)}>Copy output</button><button onClick={saveOpportunity} disabled={busy === "opportunity"}>{busy === "opportunity" ? "Saving…" : "Create / save Opportunity"}</button><button className="primary" onClick={() => sendToCreate(result.output, `${venture} intelligence opportunity`, result.evidence.map(item => `${item.title} (${item.provenance})`).join("; "))}>Send to Create →</button></div></section>}
    {tab === "Opportunities" && opportunities.length > 0 && <section className="panel intelligence-result"><div className="panel-title"><h2>Saved opportunities</h2><span>{opportunities.length}</span></div>{opportunities.map(item => <article className="opportunity-card" key={item.id}><b>{item.title}</b><p>{item.brief}</p><small>{item.status} · {new Date(item.createdAt).toLocaleString()}</small><button className="primary" onClick={() => sendToCreate(item.brief, item.title, "Saved Competitor Intelligence opportunity")}>Send to Create →</button></article>)}</section>}
    {error && <section className="creative-error">{error}</section>}
  </>;
}
