"use client";

import { useEffect, useMemo, useState } from "react";

type Competitor = { id: string; name: string; websiteUrl?: string | null; lastCollectedAt?: string | null; lastCollectionError?: string | null };
type Evidence = { id: string; competitorName: string; platform: string; distribution: string; title: string; sourceUrl?: string | null; mediaUrl?: string | null; contentText?: string | null; activityStatus?: string | null; capturedAt: string; provenance: string; observableSignals?: { publicSignal?: string|null; strengthSignal?: string|null; replicationIdea?: string|null }|null };
type Opportunity = { id: string; title: string; brief: string; status: string; createdAt: string };
type SkillRun = { id: string; output: string; evidence: Array<{ id: string; title: string; sourceUrl?: string | null; provenance: string }> };
type ImportedSkill = { id: string; name: string; active: boolean };
type SuggestedCompetitor = { name:string; websiteUrl:string; instagramUrl?:string|null; facebookUrl?:string|null; youtubeUrl?:string|null; reason:string; focus:string };
type OwnedPost = { id:string; caption:string; permalink?:string|null; mediaType:string; mediaUrl?:string|null; timestamp?:string|null; likes:number; comments:number; reach:number; saves:number; shares:number; views:number; avgWatchMs?:number|null; skipRate?:number|null };

const tabs = ["Overview", "Your Content", "Competitors", "Outliers", "Swipe File"];

export default function IntelligenceStudio({ setView }: { setView: (view: string) => void }) {
  const ventureOptions=["Bubble Leisure","Brilliant AI Automation","FireComplianceUK","Bankole & Associates","TradeCompare","Lucky Studios","SAYAH","Oddly","TripleMMM"];
  const [venture,setVenture]=useState("SAYAH");
  const [ventureId,setVentureId]=useState("");
  const [tab, setTab] = useState("Overview");
  const [competitors, setCompetitors] = useState<Competitor[]>([]);
  const [evidence, setEvidence] = useState<Evidence[]>([]);
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]);
  const [skills, setSkills] = useState<ImportedSkill[]>([]);
  const [selected, setSelected] = useState<string[]>([]);
  const [skill, setSkill] = useState("Niche Hacking");
  const [scope, setScope] = useState("one creative");
  const [result, setResult] = useState<SkillRun | null>(null);
  const [newCompetitor, setNewCompetitor] = useState({ name: "Bubble Boy Events", websiteUrl: "https://www.bubbleboyevents.co.uk/" });
  const [capture, setCapture] = useState({ url: "", note: "", interaction: "SAVED", distribution: "ORGANIC" });
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [ownedPosts,setOwnedPosts]=useState<OwnedPost[]>([]);
  const [ownedStatus,setOwnedStatus]=useState("Loading owned content…");
  const [suggestedCompetitors,setSuggestedCompetitors]=useState<SuggestedCompetitor[]>([]);

  const load = async () => {
    setError(null);
    const response = await fetch(`/api/intelligence/competitors?venture=${encodeURIComponent(venture)}`, { cache: "no-store" });
    const data = await response.json() as { ventureId?: string; competitors?: Competitor[]; evidence?: Evidence[]; opportunities?: Opportunity[]; error?: string };
    if (!response.ok) { setError(data.error ?? "Competitor Intelligence could not load."); return; }
    setVentureId(data.ventureId ?? ""); setCompetitors(data.competitors ?? []); setEvidence(data.evidence ?? []); setOpportunities(data.opportunities ?? []);
    const skillResponse = await fetch("/api/skills", { cache: "no-store" });
    if (skillResponse.ok) { const skillData = await skillResponse.json() as { skills?: ImportedSkill[] }; setSkills(skillData.skills ?? []); }
  };
  useEffect(() => { void load(); }, [venture]);
  useEffect(()=>{ let live=true; setOwnedPosts([]); setOwnedStatus("Loading owned content…"); fetch(`/api/integrations/instagram?venture=${encodeURIComponent(venture)}`,{cache:"no-store"}).then(async r=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>{if(!live)return;setOwnedPosts(ok?(data.posts??[]):[]);setOwnedStatus(data.connected?`${data.account} · live Instagram data`:data.message??"Not connected");}).catch(()=>live&&setOwnedStatus("Owned social data unavailable")); return()=>{live=false}; },[venture]);
  const filtered = useMemo(() => evidence.filter(item => tab === "Inspiration" ? item.competitorName === "Manual capture" || item.activityStatus === "SAVED" : true), [evidence, tab]);
  const campaignEvidence = useMemo(() => filtered.filter(item => item.platform !== "WEB"), [filtered]);
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  const captureSocial = async () => {
    setBusy("capture"); setError(null); setNotice(null);
    try {
      const response = await fetch("/api/intelligence/capture", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ venture, ...capture }) });
      const responseText = await response.text();
      let data: { evidence?: Evidence; notice?: string; error?: string };
      try { data = JSON.parse(responseText) as typeof data; } catch { throw new Error(responseText.slice(0, 300) || `Capture failed (${response.status}).`); }
      if (!response.ok || !data.evidence) throw new Error(data.error ?? "Public social source could not be captured.");
      setCapture(current => ({ ...current, url: "", note: "" }));
      setNotice(data.notice ?? "Public source captured.");
      await load();
      setSelected(current => data.evidence ? [...new Set([...current, data.evidence.id])] : current);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Public social source could not be captured."); }
    finally { setBusy(null); }
  };
  const discoverCompetitors = async () => { setBusy("discover"); setError(null); try { const response=await fetch("/api/intelligence/competitors/discover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({venture})}); const data=await response.json() as {competitors?:SuggestedCompetitor[];error?:string}; if(!response.ok) throw new Error(data.error??"Competitor research failed."); setSuggestedCompetitors(data.competitors??[]); } catch(cause){setError(cause instanceof Error?cause.message:"Competitor research failed.");} finally{setBusy(null);} };
  const trackSuggested = async (item:SuggestedCompetitor) => { setBusy(`track-${item.name}`); setError(null); try { const response=await fetch("/api/intelligence/competitors",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({venture,name:item.name,websiteUrl:item.websiteUrl,instagramUrl:item.instagramUrl??undefined,facebookUrl:item.facebookUrl??undefined,youtubeChannelUrl:item.youtubeUrl??undefined})}); const data=await response.json() as {error?:string}; if(!response.ok) throw new Error(data.error??"Competitor could not be tracked."); setSuggestedCompetitors(current=>current.filter(x=>x.name!==item.name)); await load(); } catch(cause){setError(cause instanceof Error?cause.message:"Competitor could not be tracked.");} finally{setBusy(null);} };
  const addCompetitor = async () => { setBusy("add"); setError(null); try { const response = await fetch("/api/intelligence/competitors", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ venture, ...newCompetitor }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "Competitor could not be saved."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Competitor could not be saved."); } finally { setBusy(null); } };
  const collect = async (competitor: Competitor) => { setBusy(competitor.id); setError(null); try { const response = await fetch(`/api/intelligence/competitors/${competitor.id}/collect`, { method: "POST" }); const data = await response.json() as { error?: string; notice?: string }; if (!response.ok) throw new Error(data.error ?? "Collection failed."); if (data.notice) setError(data.notice); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Collection failed."); } finally { setBusy(null); } };
  const researchCompetitor = async (competitor: Competitor) => { setBusy(`research-${competitor.id}`); setError(null); setNotice(null); try { const response=await fetch("/api/intelligence/competitors/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({competitorId:competitor.id})}); const raw=await response.text(); let data:{error?:string;notice?:string}={}; try{data=raw?JSON.parse(raw):{};}catch{throw new Error(response.status===504?"Research took too long. HQ has not lost your existing evidence — try this competitor again.":"Research service returned an invalid response. Please try again.");} if(!response.ok) throw new Error(data.error??`Campaign research failed (${response.status}).`); setNotice(data.notice??"Campaign research added."); await load(); } catch(cause){setError(cause instanceof Error?cause.message:"Campaign research failed.");} finally{setBusy(null);} };
  const addStarters = async () => { setBusy("starters"); setError(null); try { const response = await fetch("/api/intelligence/competitors/starter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ venture }) }); const data = await response.json() as { error?: string; notice?: string }; if (!response.ok) throw new Error(data.error ?? "Public sources could not be added."); setError(data.notice ?? null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Public sources could not be added."); } finally { setBusy(null); } };
  const collectAll = async () => { setBusy("all"); setError(null); try { for (const competitor of competitors) await collect(competitor); } finally { setBusy(null); } };
  const runSkill = async () => { setBusy("skill"); setError(null); setResult(null); try { const response = await fetch("/api/intelligence/run-skill", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ventureId, skillName: skill, evidenceIds: selected, scope: { mode: scope, source: "Competitor Intelligence" } }) }); const data = await response.json() as { run?: SkillRun; error?: string }; if (!response.ok || !data.run) throw new Error(data.error ?? "Approved skill did not run."); setResult(data.run); } catch (cause) { setError(cause instanceof Error ? cause.message : "Approved skill did not run."); } finally { setBusy(null); } };
  const saveOpportunity = async () => { if (!result) return; setBusy("opportunity"); setError(null); try { const response = await fetch("/api/intelligence/opportunities", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ venture, title: `${skill} opportunity`, brief: result.output, evidenceId: selected[0], skillRunId: result.id }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "Opportunity could not be saved."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Opportunity could not be saved."); } finally { setBusy(null); } };
  const sendToCreate = (brief: string, title: string, sources: string) => { sessionStorage.setItem("bankole-hq:create-handoff", JSON.stringify({ venture, project: title, skill: result ? skill : "Observed intelligence", output: brief, sourceEvidence: sources })); setView("Create"); };
  const sendToAskHQ = () => {
    const sources = evidence.filter(item => selected.includes(item.id));
    sessionStorage.setItem("bankole-hq:workflow-handoff", JSON.stringify({
      venture,
      sourceEvidenceIds: selected,
      sourceContext: sources.map(item => `[${item.id}] ${item.title}\n${item.contentText ?? ""}\nSource: ${item.sourceUrl ?? "Not captured"}\nProvenance: ${item.provenance}`).join("\n\n"),
      outcome: `Find me new ${venture} opportunities from the selected competitor intelligence`,
    }));
    setView("Ask HQ");
  };

  const saveToSwipeFile = async (item: Evidence, saved = true) => { setBusy(`swipe-${item.id}`); setError(null); try { const response=await fetch("/api/intelligence/swipe-file",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({evidenceId:item.id,saved})}); const data=await response.json() as {error?:string}; if(!response.ok) throw new Error(data.error??"Swipe File could not be updated."); setNotice(saved?"Saved to Swipe File.":"Removed from Swipe File."); await load(); } catch(cause){setError(cause instanceof Error?cause.message:"Swipe File could not be updated.");} finally{setBusy(null);} };
  const swipeItems = evidence.filter(item => item.activityStatus === "SAVED");
  const outlierItems = evidence.filter(item => item.activityStatus === "OUTLIER" || item.contentType === "OUTLIER_VIDEO");
  const approvedSkills = skills.filter((item) => item.active);
  return <>
    <section className="exec-hero intelligence-hero"><div><p className="eyebrow">INTELLIGENCE</p><h2>What should we do next?</h2><p>Use your own results when they exist. When they do not, learn from the market, competitors and examples you find.</p></div><button className="primary" onClick={() => setTab("Competitors")}>＋ Add competitor or example</button></section>
    <section className="brand-switcher"><div><b>Working on</b><small>Everything below changes with the selected business.</small></div><label><select value={venture} onChange={e=>{setVenture(e.target.value);setSelected([]);setResult(null)}}>{ventureOptions.map(v=><option key={v}>{v}</option>)}</select></label></section>
    <nav className="intel-tabs">{tabs.map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
    {tab === "Competitors" && <section className="panel competitor-discovery"><div className="competitor-mode-banner"><div><span>MARKET WATCH</span><b>See what competitors are running — and what is worth testing.</b><p>HQ checks social, Meta, Google Ads, YouTube and websites, then turns observable campaign signals into tests for your business.</p></div><div className="market-watch-stat"><strong>{competitors.length}</strong><small>brands watched</small></div></div><div className="panel-title"><div><p className="section-kicker">DISCOVER</p><h2>Find competitors worth watching</h2><p>HQ researches the market for you. Review the suggestions, then track the useful ones.</p></div><button className="primary" onClick={discoverCompetitors} disabled={!!busy}>{busy==="discover"?"Researching the market…":suggestedCompetitors.length?"Find different competitors":"Find competitors for me →"}</button></div>{suggestedCompetitors.length>0&&<div className="competitor-card-grid">{suggestedCompetitors.map(item=>{let host="";try{host=new URL(item.websiteUrl).hostname}catch{}return <article className="competitor-card" key={item.name}><div className="competitor-identity">{host&&<img src={`https://www.google.com/s2/favicons?domain=${host}&sz=128`} alt=""/>}<div><small>{item.focus}</small><h3>{item.name}</h3></div></div><p>{item.reason}</p><div className="competitor-socials"><a href={item.websiteUrl} target="_blank" rel="noreferrer">Website ↗</a>{item.instagramUrl&&<a href={item.instagramUrl} target="_blank" rel="noreferrer">Instagram ↗</a>}{item.facebookUrl&&<a href={item.facebookUrl} target="_blank" rel="noreferrer">Facebook ↗</a>}{item.youtubeUrl&&<a href={item.youtubeUrl} target="_blank" rel="noreferrer">YouTube ↗</a>}</div><div className="competitor-actions"><button className="primary" onClick={()=>trackSuggested(item)} disabled={!!busy}>{busy===`track-${item.name}`?"Tracking…":"Track & analyse"}</button></div></article>})}</div>}</section>}
    {tab === "Competitors" && competitors.length > 0 && <section className="panel intelligence-controls"><div className="panel-title"><div><p className="section-kicker">YOUR WATCHLIST</p><h2>Who should we investigate?</h2><p>Research a brand to pull recent public posts, videos and campaigns into the feed below.</p></div><span>{competitors.length} tracked</span></div><div className="tracked-competitor-grid">{competitors.map(item => <article className="competitor-row" key={item.id}><div><b>{item.name}</b><small>{item.lastCollectedAt ? `Last checked ${new Date(item.lastCollectedAt).toLocaleDateString()}` : "Ready to research"}</small></div><div className="competitor-actions"><button className="primary" onClick={() => researchCompetitor(item)} disabled={!!busy}>{busy === `research-${item.id}` ? "Researching…" : "Find ads & campaigns"}</button><button onClick={() => collect(item)} disabled={!!busy}>{busy === item.id ? "Checking…" : "Check website"}</button></div></article>)}</div></section>}
    {tab === "Competitors" && <section className="panel research-inbox"><div className="research-heading"><div><p className="section-kicker">INSPIRATION</p><h2>Seen something worth learning from?</h2><p>Drop the link here. HQ will keep it with the rest of your market intelligence.</p></div></div><div className="research-grid"><label className="research-field research-url"><span>Public post or video link</span><input value={capture.url} onChange={event => setCapture({ ...capture, url: event.target.value })} placeholder="Paste an Instagram, Facebook, YouTube or TikTok link"/></label><label className="research-field"><span>Your interaction</span><select value={capture.interaction} onChange={event => setCapture({ ...capture, interaction: event.target.value })}><option value="SAVED">I saved it</option><option value="LIKED">I liked it</option><option value="SAW">I noticed it</option><option value="COMPETITOR">Competitor research</option></select></label><label className="research-field"><span>Content source</span><select value={capture.distribution} onChange={event => setCapture({ ...capture, distribution: event.target.value })}><option value="ORGANIC">Organic content</option><option value="PAID">Paid advertisement</option></select></label><label className="research-field research-note"><span>What caught your attention?</span><textarea rows={4} value={capture.note} onChange={event => setCapture({ ...capture, note: event.target.value })} placeholder="Example: The first-second hook, genuine parent reaction and quick pacing would suit a Bubble Leisure ad."/></label></div><div className="research-footer"><div><button className="primary capture-button" onClick={captureSocial} disabled={!!busy || !capture.url.trim()}>{busy === "capture" ? "Collecting public evidence…" : "Capture this content →"}</button><small>Only the link you paste is collected. HQ cannot read your private Saved or Likes folders.</small></div><div className="next-step"><b>Then HQ can</b><span>compare the example with your competitors and turn useful patterns into ideas or actions.</span></div></div>{notice && <div className="capture-success">{notice}</div>}</section>}
    {tab === "Your Content" && <section className="panel wide"><div className="panel-title"><div><p className="section-kicker">YOUR CONTENT</p><h2>{venture} posts & performance</h2></div><span>{ownedStatus}</span></div>{ownedPosts.length===0?<div className="create-empty"><b>No owned posts available yet.</b><p>{ownedStatus}</p></div>:<div className="owned-content-grid">{ownedPosts.map(p=><article className="owned-post" key={p.id}>{p.mediaUrl&&(p.mediaType.includes("REEL")||p.mediaType.includes("VIDEO")?<video src={p.mediaUrl} muted playsInline/>:<img src={p.mediaUrl} alt="Published content"/>)}<div><small>{p.mediaType} · {p.timestamp?new Date(p.timestamp).toLocaleDateString():""}</small><p>{p.caption}</p><div className="post-metrics"><span><b>{p.views.toLocaleString()}</b> views</span><span><b>{p.reach.toLocaleString()}</b> reach</span><span><b>{p.likes}</b> likes</span><span><b>{p.comments}</b> comments</span><span><b>{p.saves}</b> saves</span><span><b>{p.shares}</b> shares</span></div>{p.permalink&&<a href={p.permalink} target="_blank" rel="noreferrer">Open post ↗</a>}</div></article>)}</div>}</section>}
    {tab === "Overview" && <section className="panel wide"><div className="panel-title"><div><p className="section-kicker">LIVE VENTURE VIEW</p><h2>{venture} at a glance</h2></div><span>{competitors.length} competitors · {evidence.length} evidence records</span></div><section className="metric-grid four"><article className="metric"><small>COMPETITORS</small><b>{competitors.length}</b><p>tracked for this venture</p></article><article className="metric"><small>PUBLIC EVIDENCE</small><b>{evidence.length}</b><p>captured records</p></article><article className="metric"><small>PAID / ORGANIC</small><b>{evidence.filter(x=>x.distribution==="PAID").length} / {evidence.filter(x=>x.distribution==="ORGANIC").length}</b><p>observed split</p></article><article className="metric"><small>OPPORTUNITIES</small><b>{opportunities.length}</b><p>saved from analysis</p></article></section><div className="closing-list">{competitors.map(x=><div key={x.id}><span><b>{x.name}</b><small>{x.lastCollectedAt?`Last collected ${new Date(x.lastCollectedAt).toLocaleDateString()}`:"Collection required"}</small></span><strong>{evidence.filter(e=>e.competitorName===x.name).length} items</strong></div>)}</div></section>}{tab === "Competitors" && <section className="intelligence-workspace"><section className="panel intelligence-controls"><div className="panel-title"><div><p className="section-kicker">TRACKING</p><h2>Your competitor watchlist</h2></div><span>{competitors.length} tracked</span></div><details className="advanced-options"><summary>Add one HQ missed</summary><label>Name<input value={newCompetitor.name} onChange={event => setNewCompetitor({ ...newCompetitor, name: event.target.value })}/></label><label>Website<input value={newCompetitor.websiteUrl} onChange={event => setNewCompetitor({ ...newCompetitor, websiteUrl: event.target.value })}/></label><button className="primary" onClick={addCompetitor} disabled={!!busy}>{busy === "add" ? "Saving…" : "Add competitor"}</button><p className="note">Use this only when you already know a competitor HQ did not find.</p></details>{competitors.length > 1 && <button onClick={collectAll} disabled={!!busy}>{busy === "all" ? "Checking competitors…" : "Refresh all"}</button>}{competitors.map(item => <article className="competitor-row" key={item.id}><b>{item.name}</b><small>{item.lastCollectedAt ? `Collected ${new Date(item.lastCollectedAt).toLocaleString()}` : "Not collected"}</small>{item.lastCollectionError && <small className="error-text">{item.lastCollectionError}</small>}<div className="competitor-actions"><button className="primary" onClick={() => researchCompetitor(item)} disabled={!!busy}>{busy === `research-${item.id}` ? "Researching…" : "Find posts & campaigns"}</button><button onClick={() => collect(item)} disabled={!!busy}>{busy === item.id ? "Checking…" : "Check website"}</button></div></article>)}</section>
      <section className="panel evidence-panel"><div className="panel-title creative-feed-head"><div><p className="section-kicker">CREATIVE FEED</p><h2>What competitors are putting into the market</h2><p>Real ads, posts and campaigns. Use the strongest ideas to inspire your next test.</p></div><span>{campaignEvidence.length} verified campaign records</span></div>{campaignEvidence.length === 0 ? <div className="create-empty"><b>No verified ads found yet.</b><br/>Website screenshots are kept out of this feed. Use Find ads & campaigns above to research Meta, Instagram, Google Ads and YouTube.</div> : <div className="campaign-grid">{campaignEvidence.map(item => { const strength=item.observableSignals?.strengthSignal; const idea=item.observableSignals?.replicationIdea; return <article key={item.id} className="campaign-card"><div className="campaign-visual">{item.mediaUrl ? <img src={item.mediaUrl} alt="Observed competitor creative"/> : <div className="campaign-placeholder"><span>{item.platform}</span><b>{item.title}</b></div>}<span className="platform-pill">{item.platform==="META"?"Meta Ads":item.platform==="GOOGLE_ADS"?"Google Ads":item.platform}</span>{strength&&<span className={`strength-pill strength-${strength.toLowerCase()}`}>{strength}</span>}</div><div className="campaign-body"><label className="campaign-title"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)}/><span><b>{item.title}</b><small>{item.competitorName}</small></span></label><p>{item.contentText}</p>{idea&&<div className="campaign-idea"><small>TEST FOR {venture.toUpperCase()}</small><span>{idea}</span></div>}<div className="campaign-actions">{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer">View ↗</a>}<button onClick={()=>saveToSwipeFile(item)} disabled={busy===`swipe-${item.id}`}>{busy===`swipe-${item.id}`?"Saving…":"Save to Swipe File"}</button><button className="primary" onClick={() => sendToCreate(idea||item.contentText||item.title,`${venture} version of ${item.title}`,`${item.competitorName} · ${item.platform} · ${item.provenance}`)}>Create our version →</button></div></div></article>})}</div>}</section></section>}
    {tab === "Outliers" && <section className="panel evidence-panel"><div className="panel-title creative-feed-head"><div><p className="section-kicker">OUTLIER RADAR</p><h2>Breakout content in {venture}</h2><p>Videos performing unusually well versus each creator's normal baseline. Powered by vidIQ research and filtered into HQ evidence.</p></div><span>{outlierItems.length} outliers</span></div>{outlierItems.length===0?<div className="create-empty"><b>No outliers imported for this business yet.</b><p>HQ keeps this separate from generic trending content so irrelevant keyword matches do not pollute your Swipe File.</p></div>:<div className="campaign-grid">{outlierItems.map(item=>{const sig=item.observableSignals;return <article key={item.id} className="campaign-card"><div className="campaign-visual">{item.mediaUrl?<img src={item.mediaUrl} alt="Outlier thumbnail"/>:<div className="campaign-placeholder"><span>YOUTUBE</span><b>{item.title}</b></div>}<span className="platform-pill">OUTLIER</span></div><div className="campaign-body"><div className="campaign-title"><span><b>{item.title}</b><small>{item.competitorName}</small></span><em className={`strength-pill ${(sig?.strengthSignal||"LOW").toLowerCase()}`}>{sig?.strengthSignal||"OUTLIER"}</em></div>{sig?.publicSignal&&<p>{sig.publicSignal}</p>}<div className="campaign-actions">{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer">Watch ↗</a>}<button onClick={()=>saveToSwipeFile(item)} disabled={busy===`swipe-${item.id}`}>Save to Swipe File</button><button className="primary" onClick={()=>sendToCreate(item.title,`${venture} version of ${item.title}`,`${item.competitorName} · vidIQ outlier`)}>Create our version →</button></div></div></article>})}</div>}</section>}
    {tab === "Swipe File" && <section className="panel evidence-panel"><div className="panel-title creative-feed-head"><div><p className="section-kicker">SWIPE FILE</p><h2>Your saved creative library</h2><p>Instagram saves, competitor campaigns and ideas worth reusing — one place for every business.</p></div><span>{swipeItems.length} saved</span></div>{swipeItems.length===0?<div className="create-empty"><b>Your Swipe File is empty.</b><p>Save a campaign from Competitors or capture a post you want to keep. Instagram Saver will feed this library as it is connected.</p></div>:<div className="campaign-grid">{swipeItems.map(item=>{const idea=item.observableSignals?.replicationIdea;return <article key={item.id} className="campaign-card"><div className="campaign-visual">{item.mediaUrl?<img src={item.mediaUrl} alt="Saved creative"/>:<div className="campaign-placeholder"><span>{item.platform}</span><b>{item.title}</b></div>}<span className="platform-pill">{item.platform}</span></div><div className="campaign-body"><div className="campaign-title"><span><b>{item.title}</b><small>{item.competitorName}</small></span></div><p>{item.contentText}</p>{idea&&<div className="campaign-idea"><small>HOW WE COULD USE IT</small><span>{idea}</span></div>}<div className="campaign-actions">{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer">View original ↗</a>}<button onClick={()=>saveToSwipeFile(item,false)} disabled={busy===`swipe-${item.id}`}>Remove</button><button className="primary" onClick={()=>sendToCreate(idea||item.contentText||item.title,`${venture} version of ${item.title}`,`${item.competitorName} · ${item.platform}`)}>Create our version →</button></div></div></article>})}</div>}</section>}
    {selected.length > 0 && <section className="panel skill-runner"><div className="panel-title"><div><p className="section-kicker">NEXT STEP</p><h2>What do you want HQ to do?</h2></div><span>{selected.length} selected evidence item{selected.length === 1 ? "" : "s"}</span></div><div className="skill-controls"><button className="primary" onClick={runSkill} disabled={busy === "skill" || !selected.length || !approvedSkills.length}>{busy === "skill" ? "Analysing…" : "Analyse selected"}</button><button onClick={sendToAskHQ} disabled={!selected.length}>Ask HQ to build workflow →</button></div><p className="note">HQ chooses the approved analysis method in the background. You choose the outcome, not the tool.</p></section>}
    {result && <section className="panel intelligence-result"><div className="panel-title"><h2>HQ analysis</h2><span className="badge needs-approval">Based on selected evidence</span></div><pre>{result.output}</pre><div className="evidence-links"><b>Source evidence</b>{result.evidence.map(item => <span key={item.id}>{item.title} · {item.provenance}</span>)}</div><div className="output-actions"><button onClick={() => navigator.clipboard?.writeText(result.output)}>Copy output</button><button onClick={saveOpportunity} disabled={busy === "opportunity"}>{busy === "opportunity" ? "Saving…" : "Create / save Opportunity"}</button><button className="primary" onClick={() => sendToCreate(result.output, `${venture} intelligence opportunity`, result.evidence.map(item => `${item.title} (${item.provenance})`).join("; "))}>Use this idea → Create</button></div></section>}
    {opportunities.length > 0 && <section className="panel intelligence-result"><div className="panel-title"><h2>Saved opportunities</h2><span>{opportunities.length}</span></div>{opportunities.map(item => <article className="opportunity-card" key={item.id}><b>{item.title}</b><p>{item.brief}</p><small>{item.status} · {new Date(item.createdAt).toLocaleString()}</small><button className="primary" onClick={() => sendToCreate(item.brief, item.title, "Saved Competitor Intelligence opportunity")}>Send to Create →</button></article>)}</section>}
    {error && <section className="creative-error">{error}</section>}
  </>;
}
