"use client";
import {useEffect,useState} from "react";
type Props={openBusiness:(name:string)=>void;openCreate:(brand?:string,objective?:string)=>void;openIntelligence:()=>void};
type Item={id:string;business:string;type:string;title:string;detail:string;action:string;source?:string};
type Today={generatedAt:string;dataPolicy?:string;metrics:{ventures:number;openTasks:number;activeLeads:number;activeDeals:number;opportunities:number;approvals:number;pipelineValue:number;leadValue:number;recordedRevenue:number};queue:Item[];integrations?:Record<string,string>};
const gbp=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(n);
export default function TodayDashboard({openBusiness,openCreate,openIntelligence}:Props){
 const [data,setData]=useState<Today|null>(null);const[error,setError]=useState("");
 const load=()=>fetch("/api/today",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||"Could not load HQ data.");setData(x)}).catch(e=>setError(e.message));
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),60000);return()=>clearInterval(timer)},[]);
 const groups=data?.queue.reduce((a,x)=>{(a[x.business]??=[]).push(x);return a},{} as Record<string,Item[]>)??{};
 return <><section className="exec-hero command-hero"><div><p className="eyebrow">TODAY · REVENUE COMMAND CENTRE</p><h2>What can move money today?</h2><p>Live HQ records plus your current operating context. No demo pipeline is generated here.</p></div><button className="primary" onClick={()=>load()}>↻ Refresh live data</button></section>
 {error&&<section className="creative-error"><b>HQ data unavailable.</b><br/>{error}</section>}
 {data&&<><section className="metric-grid commercial-metrics"><Metric label="Active leads" value={String(data.metrics.activeLeads)} hint={gbp(data.metrics.leadValue)+" estimated"}/><Metric label="Active deals" value={String(data.metrics.activeDeals)} hint={gbp(data.metrics.pipelineValue)+" recorded value"}/><Metric label="Opportunities" value={String(data.metrics.opportunities)} hint="live HQ records"/><Metric label="Recorded revenue" value={gbp(data.metrics.recordedRevenue)} hint="HQ revenue entries"/><Metric label="Approvals" value={String(data.metrics.approvals)} hint="waiting on you"/></section>
 <section className="panel wide"><div className="panel-title"><div><p className="eyebrow">MONEY-FIRST QUEUE</p><h2>Highest-value moves now</h2></div><span className="live-pill">UPDATED {new Date(data.generatedAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div>{data.queue.slice(0,8).map(x=><Action key={x.id} x={x} openBusiness={openBusiness} openIntelligence={openIntelligence}/>)}</section>
 <section className="panel wide"><div className="panel-title"><div><p className="eyebrow">BY BUSINESS</p><h2>Current operating picture</h2></div><span>Revenue priorities first</span></div><div className="action-lanes">{Object.entries(groups).map(([business,items])=><div className="action-lane" key={business}><h2>{business} <b>{items.length}</b></h2>{items.slice(0,5).map(x=><Action key={x.id} x={x} openBusiness={openBusiness} openIntelligence={openIntelligence}/>)}</div>)}</div></section>
 <section className="panel wide"><div className="panel-title"><div><p className="eyebrow">DATA CONNECTIONS</p><h2>What is actually live?</h2></div><span>Auto-refresh every 60s</span></div><div className="closing-list">{Object.entries(data.integrations??{}).map(([name,status])=><div key={name}><span><b>{name.replace(/([A-Z])/g," $1")}</b><small>{status}</small></span></div>)}</div><p className="note">{data.dataPolicy}</p></section></>}
 {!data&&!error&&<section className="panel wide"><p>Reading HQ records…</p></section>}</>
}
function Action({x,openBusiness,openIntelligence}:{x:Item;openBusiness:(n:string)=>void;openIntelligence:()=>void}){const go=()=>x.action==="intelligence"?openIntelligence():x.business!=="HQ"&&openBusiness(x.business);return <button className="attention-row action-visual" onClick={go}><span className={"signal "+x.type.toLowerCase()}/><span><b>{x.title}</b><small>{x.business} · {x.detail}</small>{x.source&&<small>Source: {x.source}</small>}</span><em>{x.type}</em><strong>→</strong></button>}
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <div className="metric metric-visual blue"><p>{label}</p><strong>{value}</strong><small>{hint}</small></div>}
