"use client";
import {useEffect,useState} from "react";
type Props={openBusiness:(name:string)=>void;openCreate:(brand?:string,objective?:string)=>void;openIntelligence:()=>void};
type Item={id:string;business:string;type:string;title:string;detail:string;action:string};
type Today={metrics:{ventures:number;openTasks:number;activeLeads:number;activeDeals:number;opportunities:number;approvals:number};queue:Item[]};
export default function TodayDashboard({openBusiness,openCreate,openIntelligence}:Props){
 const [data,setData]=useState<Today|null>(null);const[error,setError]=useState("");
 useEffect(()=>{fetch("/api/today",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||"Could not load HQ data.");setData(x)}).catch(e=>setError(e.message))},[]);
 const groups=data?.queue.reduce((a,x)=>{(a[x.type]??=[]).push(x);return a},{} as Record<string,Item[]>)??{};
 return <><section className="exec-hero command-hero"><div><p className="eyebrow">TODAY · COMMAND CENTRE</p><h2>See the business. Spot the bottleneck. Move the money.</h2><p>Commercial overview first; actions second. Everything below is drawn from stored HQ records.</p></div><button className="primary" onClick={()=>openCreate()}>＋ Create</button></section>
 {error&&<section className="creative-error"><b>HQ data unavailable.</b><br/>{error}</section>}
 {data&&<><section className="metric-grid commercial-metrics"><Metric icon="◎" label="Active leads" value={data.metrics.activeLeads} tone="blue"/><Metric icon="£" label="Active deals" value={data.metrics.activeDeals} tone="lime"/><Metric icon="◆" label="Opportunities" value={data.metrics.opportunities} tone="purple"/><Metric icon="!" label="Open tasks" value={data.metrics.openTasks} tone="orange"/><Metric icon="✓" label="Approvals" value={data.metrics.approvals} tone="purple"/></section>
 <section className="split overview-split"><div className="panel pipeline-panel"><div className="panel-title"><div><p className="eyebrow">SALES & DEAL FLOW</p><h2>Pipeline overview</h2></div><span className="live-pill">LIVE RECORDS</span></div><div className="pipeline-bars">
 <Pipeline label="Leads" n={data.metrics.activeLeads} max={Math.max(data.metrics.activeLeads,data.metrics.activeDeals,data.metrics.opportunities,1)} tone="blue"/>
 <Pipeline label="Deals" n={data.metrics.activeDeals} max={Math.max(data.metrics.activeLeads,data.metrics.activeDeals,data.metrics.opportunities,1)} tone="lime"/>
 <Pipeline label="Opportunities" n={data.metrics.opportunities} max={Math.max(data.metrics.activeLeads,data.metrics.activeDeals,data.metrics.opportunities,1)} tone="purple"/>
 </div><p className="note">Next upgrade: stage values, weighted pipeline and revenue by venture from the underlying records.</p></div>
 <div className="panel next-panel"><div className="panel-title"><div><p className="eyebrow">NEXT MOVES</p><h2>Needs your attention</h2></div><b className="attention-count">{data.queue.length}</b></div>{data.queue.slice(0,4).map(x=><Action key={x.id} x={x} openBusiness={openBusiness} openIntelligence={openIntelligence}/>)}{!data.queue.length&&<p className="create-empty">No actionable records stored.</p>}</div></section>
 <section className="panel wide"><div className="panel-title"><div><p className="eyebrow">OPERATING QUEUE</p><h2>Work by type</h2></div><span>Scan → choose → act</span></div><div className="action-lanes">{Object.entries(groups).map(([type,items])=><div className="action-lane" key={type}><h2>{type} <b>{items.length}</b></h2>{items.slice(0,4).map(x=><Action key={x.id} x={x} openBusiness={openBusiness} openIntelligence={openIntelligence}/>)}</div>)}</div></section></>}
 {!data&&!error&&<section className="panel wide"><p>Reading HQ records…</p></section>}</>
}
function Action({x,openBusiness,openIntelligence}:{x:Item;openBusiness:(n:string)=>void;openIntelligence:()=>void}){const go=()=>x.action==="intelligence"?openIntelligence():x.business!=="HQ"&&openBusiness(x.business);return <button className="attention-row action-visual" onClick={go}><span className={"signal "+x.type.toLowerCase()}/><span><b>{x.title}</b><small>{x.business} · {x.detail}</small></span><em>{x.type}</em><strong>→</strong></button>}
function Metric({icon,label,value,tone}:{icon:string;label:string;value:number;tone:string}){return <div className={"metric metric-visual "+tone}><span className="metric-icon">{icon}</span><p>{label}</p><strong>{value}</strong><small>live HQ records</small></div>}
function Pipeline({label,n,max,tone}:{label:string;n:number;max:number;tone:string}){return <div className="pipeline-row"><span>{label}</span><i><b className={tone} style={{width:Math.max(5,(n/max)*100)+"%"}}/></i><strong>{n}</strong></div>}