"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import launch from "../../content/campaign-studio/launch-wave-1.json";
const founder="https://d2ol7oe51mr4n9.cloudfront.net/user_3IabZNH0RerpywVzXhojSNw3wCG/3c653dbd-c347-4b31-942d-e6be63a03787.png";
const tones:Record<string,string>={"BAA":"#85bbff","Bubble Leisure":"#b8ef64","FireComplianceUK":"#e4a09d","Bankole & Associates":"#dfbd7d"};
export default function CampaignStudio(){
 const [avatars,setAvatars]=useState<Record<string,string>>({});
 const [brand,setBrand]=useState("All");
 const [error,setError]=useState("");
 const [loading,setLoading]=useState(true);
 const [copied,setCopied]=useState("");
 
 const [assets,setAssets]=useState<Record<string,string>>({});
 const [pending,setPending]=useState<Record<string,{imageUrl:string;postId:string;slide:number;status:string}>>({});
 const [busy,setBusy]=useState("");
 const [reviewMessage,setReviewMessage]=useState("");
 
 
 useEffect(()=>{fetch("/api/campaign-studio/assets?avatars=1",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||"Could not load saved avatars");const next:Record<string,string>={};for(const a of d.avatars||[])next[a.brand]=a.imageUrl;setAvatars(next)}).catch(e=>setError(e instanceof Error?e.message:"Avatar loading failed")).finally(()=>setLoading(false))},[]);
 useEffect(()=>{fetch("/api/campaign-studio/assets",{cache:"no-store"}).then(r=>r.json()).then(d=>{const m:Record<string,string>={};const q:Record<string,{imageUrl:string;postId:string;slide:number;status:string}>={};for(const a of d.assets||[]){if(a.postId&&a.imageUrl&&a.status==="approved")m[a.postId]=a.imageUrl;else if(a.postId&&a.imageUrl&&a.status!=="rejected")q[a.postId]=a;}setAssets(m);setPending(q)}).catch(()=>{})},[]);
 const refresh=async()=>{const r=await fetch("/api/campaign-studio/assets",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"Could not refresh assets");const m:Record<string,string>={},q:Record<string,{imageUrl:string;postId:string;slide:number;status:string}>={};for(const a of d.assets||[]){if(a.postId&&a.imageUrl&&a.status==="approved")m[a.postId]=a.imageUrl;else if(a.postId&&a.imageUrl&&a.status!=="rejected")q[a.postId]=a;}setAssets(m);setPending(q)};
 const review=async(postId:string,action:"approve"|"reject")=>{setBusy(postId);setReviewMessage("");try{const r=await fetch("/api/campaign-studio/assets",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({postId,slide:pending[postId]?.slide||0,action})});const d=await r.json();if(!r.ok)throw Error(d.error||"Review failed");await refresh();setReviewMessage(action==="approve"?"Approved and attached to the correct HQ post. Not published.":"Rejected creative removed from review queue.")}catch(e){setReviewMessage(e instanceof Error?e.message:"Review failed")}finally{setBusy("")}};
 const generate=async(p:(typeof launch.posts)[number])=>{setBusy(p.postId);setReviewMessage("");const scenes=["candid wide environmental photograph with several people interacting, natural movement, documentary lens","close-up of authentic hands and real work materials, natural window light, editorial photography","over-the-shoulder scene showing the service in action, asymmetric composition, realistic imperfections","architectural or workplace detail with people in the background, understated premium commercial photography","unexpected overhead editorial composition with objects relevant to the business, tactile textures"];const index=launch.posts.findIndex(x=>x.postId===p.postId);const scene=scenes[index%scenes.length];const prompt="Create a distinctive premium social media campaign photograph for "+p.brand+". Message: "+p.hook+". Context: "+p.caption+". Visual direction: "+scene+". Show a believable real-world situation appropriate to the brand. Every campaign must have a different camera angle, composition, location and subject activity. Authentic human proportions, real skin texture, natural light, editorial art direction, no AI gloss, no synthetic corporate stock-photo look, no cloned poses, no exaggerated smiles, no invented uniforms or certifications. No text or logos in the image; the caption will carry the copy. Do not imitate a specific person's likeness without their reference photo.";try{const r=await fetch("/api/campaign-studio/assets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brand:p.brand,postId:p.postId,topic:p.hook,prompt,aspectRatio:"portrait"})});const d=await r.json();if(!r.ok)throw Error(d.error||"Generation failed");await refresh();setReviewMessage("New creative is ready for your review; it has not been approved or published.")}catch(e){setReviewMessage(e instanceof Error?e.message:"Generation failed")}finally{setBusy("")}};
 const posts=launch.posts.filter(p=>brand==="All"||p.brand===brand);
 return <main style={{minHeight:"100vh",background:"#0a111c",color:"#f4f6f9",padding:"28px clamp(18px,4vw,64px)",fontFamily:"Inter,Arial,sans-serif"}}>
 <Link href="/" style={{color:"#a9c7e8"}}>← HQ home</Link>
 <header style={{padding:"34px 0 24px",borderBottom:"1px solid #344053"}}>
 <p style={{color:"#b7c5d8",letterSpacing:3,fontSize:12}}>BANKOLE HQ / CUSTOMER ACQUISITION</p>
 <h1 style={{fontSize:"clamp(32px,5vw,56px)",margin:"8px 0"}}>Campaign Studio</h1>
 <p style={{color:"#c0cede",maxWidth:760,lineHeight:1.6}}>Rebranded launch campaigns. 40-post campaign queue across four brands. Approved portraits below are identity references, not finished post artwork. The first BAA avatar-based launch post is already live; individual campaign artwork awaits creation and review.</p>
 <div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:22}}><span style={{padding:"12px 16px",background:"#1a2a3a",borderRadius:10}}>4 brands</span><span style={{padding:"12px 16px",background:"#1a2a3a",borderRadius:10}}>10 qualified leads per brand</span><span style={{padding:"12px 16px",background:"#1a2a3a",borderRadius:10}}>40-lead target</span></div>
 </header>
 <section style={{padding:"25px 0"}}><h2 style={{fontSize:24}}>Approved brand identities</h2>{error&&<p role="alert" style={{color:"#ffaaa7"}}>{error}</p>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:18}}>
 {["BAA","Bubble Leisure","FireComplianceUK","Bankole & Associates"].map(name=><article key={name} style={{background:"#172332",border:"1px solid #344253",borderTop:"4px solid "+tones[name],borderRadius:16,overflow:"hidden"}}>
 {(avatars[name]||(name==="Bankole & Associates"?founder:null))?<img src={avatars[name]||founder} alt={name+" approved brand presenter"} style={{width:"100%",height:260,objectFit:"cover",objectPosition:"center 28%"}}/>:<div style={{height:260,display:"grid",placeItems:"center",background:"#202e40",padding:16,textAlign:"center"}}>{loading?"Loading approved image…":"Avatar not found in HQ storage — check saved brand assignment"}</div>}
 <div style={{padding:17}}><h3 style={{margin:"0 0 8px"}}>{name}</h3><p style={{fontSize:13,color:"#b8c6d8"}}>{name==="BAA"?"Female AI automation presenter":name==="Bubble Leisure"?"Child activity presenter":name==="FireComplianceUK"?"High-vis brand presenter (not represented as a certified inspector)":"Existing founder photograph retained"}</p></div></article>)}
 </div></section>
 <section style={{padding:"15px 0 50px"}}><h2 style={{fontSize:24}}>Current launch posts</h2><p style={{color:"#b8c6d8"}}>Only completed campaign images stored in HQ are marked as ready for approval. Reference portraits are not finished post artwork.</p><p style={{color:"#b8c6d8"}}>New copy for the rebranded campaigns. These are drafts until approved and published to connected accounts.</p>
 <p role="status" style={{color:"#b6e6d4"}}>{reviewMessage}</p><nav style={{display:"flex",gap:10,flexWrap:"wrap",margin:"22px 0"}}>{["All","BAA","Bubble Leisure","FireComplianceUK","Bankole & Associates"].map(n=><button key={n} onClick={()=>setBrand(n)} style={{background:brand===n?"#b6e6d4":"#1b2b3d",color:brand===n?"#10241f":"white",border:0,borderRadius:24,padding:"11px 17px",cursor:"pointer"}}>{n}</button>)}</nav>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:20}}>{posts.map(p=><article key={p.postId} style={{background:"#172332",border:"1px solid #354459",borderRadius:17,overflow:"hidden"}}>
 {(pending[p.postId]?.imageUrl||assets[p.postId]||avatars[p.brand]||(p.brand==="Bankole & Associates"?founder:null))&&<img src={pending[p.postId]?.imageUrl||assets[p.postId]||avatars[p.brand]||founder} alt={p.brand+" campaign imagery"} style={{width:"100%",height:320,objectFit:"cover",objectPosition:"center 27%"}}/>}
 <div style={{padding:22}}><button disabled={busy===p.postId} onClick={()=>generate(p)} style={{padding:"11px 15px",marginBottom:12,background:"#b6e6d4",border:0,borderRadius:8,fontWeight:700,cursor:"pointer"}}>{busy===p.postId?"Working…":"Generate a new premium creative"}</button>{pending[p.postId]&&<div style={{border:"1px solid #b6e6d4",padding:12,borderRadius:10,marginBottom:12}}><strong>NEW CREATIVE · AWAITING YOUR APPROVAL</strong><p>Preview above. Approving links this exact image to this post in HQ; it will not publish to social media.</p><button disabled={busy===p.postId} onClick={()=>review(p.postId,"approve")} style={{padding:10,marginRight:10,cursor:"pointer"}}>Approve and attach</button><button disabled={busy===p.postId} onClick={()=>review(p.postId,"reject")} style={{padding:10,cursor:"pointer"}}>Reject</button></div>}<p style={{color:tones[p.brand],fontSize:12,letterSpacing:1.4}}>{p.brand.toUpperCase()} · {p.channel}</p><h3 style={{fontSize:24,lineHeight:1.25}}>{p.hook}</h3><p style={{whiteSpace:"pre-wrap",lineHeight:1.6,color:"#d0dae6"}}>{p.caption}</p><p style={{fontWeight:700,color:tones[p.brand]}}>CTA: {p.cta}</p><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:16}}><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(p.caption);setCopied(p.brand)}catch{setCopied("Copy unavailable — select caption text")}}} style={{background:"#b6e6d4",color:"#10241f",border:0,borderRadius:9,padding:"12px 16px",fontWeight:700,cursor:"pointer"}}>{copied===p.brand?"Caption copied ✓":"Copy full caption"}</button><a href={avatars[p.brand]||(p.brand==="Bankole & Associates"?founder:"#")} target="_blank" rel="noreferrer" style={{display:"inline-block",border:"1px solid #a6bacd",color:"white",borderRadius:9,padding:"11px 15px",textDecoration:"none"}}>Open approved image</a></div><p style={{fontSize:13,color:"#f2d8a2"}}>{p.status}</p><p style={{fontSize:12,color:"#adc4d8"}}>Creative approval: {assets[p.postId]?"Finished artwork saved in HQ":"Individual campaign artwork pending — approved brand portrait shown only as reference."}</p></div></article>)}</div></section>
 </main>
}